site_name: Datatlas
site_url: https://datatlas-erasme.github.io/docs/
site_author: Erasme
nav:
    - Home: index.md
theme:
  name: material
extra:
    generator: false
plugins:
    - search
    - mermaid2
docs_dir: data
markdown_extensions:
  - attr_list